-- Dados ficticios para testar as telas. Acrescenta registros sem apagar os existentes.
-- Execute em uma unica sessao, os vinculos usam os IDs gerados nessa sessao.
INSERT INTO `area_compartilhada` (`descricao`, `observacao`, `status`) VALUES ('Salao de festas', 'Dados ficticios para teste das telas', 'A');
SET @demo_area_compartilhada1 = LAST_INSERT_ID();
INSERT INTO `edificio` (`nome`, `quantidade_andares`, `quantidade_unidades`, `cnpj`, `ano_lancamento`, `area_total`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `numero_unidade_agua`, `numero_unidade_gas`, `formula_calculo`, `observacao`, `status`) VALUES ('Edificio Teste 1', 5, 10, '99000000000001', '2020', 1500.0, '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 1', 'AGUA-1', 'GAS-1', NULL, 'Dados ficticios para teste das telas', 'A');
SET @demo_edificio1 = LAST_INSERT_ID();
INSERT INTO `proprietario` (`nome_fantasia`, `razao_social`, `cpf`, `rg`, `cnpj`, `inscricao_estadual`, `fone1`, `fone2`, `email`, `data_nascimento`, `data_cadastro`, `estado_civil`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `observacao`, `status`) VALUES ('Ana Teste', NULL, '90000000001', '1000001', NULL, NULL, '11999990001', NULL, 'teste1@example.com', '1990-05-12', '2026-10-01', 'Solteiro', '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 1', 'Dados ficticios para teste das telas', 'A');
SET @demo_proprietario1 = LAST_INSERT_ID();
INSERT INTO `unidade` (`descricao`, `metragem_total`, `metragem_individual`, `tipo_unidade`, `observacao`, `status`, `edificio_id`) VALUES ('Apartamento 101', 85.5, 70.0, 'Apartamento', 'Dados ficticios para teste das telas', 'A', @demo_edificio1);
SET @demo_unidade1 = LAST_INSERT_ID();
INSERT INTO `unidade_condomino` (`data_aquisicao`, `data_venda`, `observacao`, `status`, `proprietario_id`, `unidade_id`) VALUES ('2026-01-01', NULL, 'Dados ficticios para teste das telas', 'A', @demo_proprietario1, @demo_unidade1);
SET @demo_unidade_condomino1 = LAST_INSERT_ID();
INSERT INTO `area_compartilhada_edificio` (`observacao`, `status`, `area_compartilhada_id`, `edificio_id`) VALUES ('Dados ficticios para teste das telas', 'A', @demo_area_compartilhada1, @demo_edificio1);
SET @demo_area_compartilhada_edificio1 = LAST_INSERT_ID();
INSERT INTO `custo_nivel1` (`descricao`, `tipo_cc`, `observacao`, `status`) VALUES ('Manutencao', 'Debito', 'Dados ficticios para teste das telas', 'A');
SET @demo_custo_nivel11 = LAST_INSERT_ID();
INSERT INTO `custo_nivel2` (`descricao`, `observacao`, `status`, `custo_nivel1_id`) VALUES ('Reparos eletricos', 'Dados ficticios para teste das telas', 'A', @demo_custo_nivel11);
SET @demo_custo_nivel21 = LAST_INSERT_ID();
INSERT INTO `fornecedor` (`nome_fantasia`, `razao_social`, `cpf`, `rg`, `cnpj`, `inscricao_estadual`, `fone1`, `fone2`, `email`, `data_nascimento`, `data_cadastro`, `estado_civil`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `observacao`, `status`) VALUES ('Eletrica Teste', NULL, '90000000001', '1000001', '99000000000001', NULL, '11999990001', NULL, 'teste1@example.com', '1990-05-12', '2026-10-01', 'Solteiro', '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 1', 'Dados ficticios para teste das telas', 'A');
SET @demo_fornecedor1 = LAST_INSERT_ID();
INSERT INTO `sindico_profissional` (`cra`, `nome_fantasia`, `razao_social`, `cpf`, `rg`, `cnpj`, `inscricao_estadual`, `fone1`, `fone2`, `email`, `data_nascimento`, `data_cadastro`, `estado_civil`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `observacao`, `status`) VALUES ('TESTE-20261002-1', 'Paulo Sindico Teste', NULL, '90000000001', '1000001', '99000000000001', NULL, '11999990001', NULL, 'teste1@example.com', '1990-05-12', '2026-10-01', 'Solteiro', '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 1', 'Dados ficticios para teste das telas', 'A');
SET @demo_sindico_profissional1 = LAST_INSERT_ID();
INSERT INTO `funcao_mandato` (`funcao`, `data_inicio`, `data_fim`, `observacao`, `status`, `edificio_id`, `proprietario_id`, `sindico_profissional_id`) VALUES ('Sindico', '2026-01-01', NULL, 'Dados ficticios para teste das telas', 'A', @demo_edificio1, @demo_proprietario1, @demo_sindico_profissional1);
SET @demo_funcao_mandato1 = LAST_INSERT_ID();
INSERT INTO `reserva` (`data_hora_inicio`, `data_hora_fim`, `observacao`, `status`, `area_compartilhada_edificio_id`, `unidade_condominio_id`) VALUES ('2026-10-05 14:00:00', '2026-10-05 18:00:00', 'Dados ficticios para teste das telas', 'A', @demo_area_compartilhada_edificio1, @demo_unidade_condomino1);
SET @demo_reserva1 = LAST_INSERT_ID();
INSERT INTO `leitura` (`data_leitura`, `mes_referencia`, `ano_referencia`, `medicao_anterior`, `medicao_atual`, `tipo`, `observacao`, `status`, `unidade_condomino_id`) VALUES ('2026-10-01', 10, 2026, 100.0, 115.5, 'Agua', 'Dados ficticios para teste das telas', 'A', @demo_unidade_condomino1);
SET @demo_leitura1 = LAST_INSERT_ID();
INSERT INTO `condominio` (`mes_referencia`, `ano_referencia`, `data_emissao`, `data_vencimento`, `data_pagamento`, `juros`, `multas`, `correcao`, `valor_emitido`, `valor_pago`, `observacao`, `status`, `unidade_condomino_id`) VALUES (10, 2026, '2026-10-01', '2026-10-10', '2026-10-02', 0, 0, 0, 350.0, 350.0, 'Dados ficticios para teste das telas', 'A', @demo_unidade_condomino1);
SET @demo_condominio1 = LAST_INSERT_ID();
INSERT INTO `movimento_caixa` (`data_emissao`, `data_vencimento`, `data_pagamento`, `valor_emitido`, `multas`, `correcao_monetaria`, `juros`, `valor_pagamento`, `tipo`, `flag_rateio`, `flag_formula`, `observacao`, `status`, `edificio_id`, `custo_nivel2_id`, `fornecedor_id`) VALUES ('2026-10-01', '2026-10-10', '2026-10-02', 850.0, 0, 0, 0, 850.0, 'Despesa', 1, NULL, 'Dados ficticios para teste das telas', 'A', @demo_edificio1, @demo_custo_nivel21, @demo_fornecedor1);
SET @demo_movimento_caixa1 = LAST_INSERT_ID();
INSERT INTO `area_compartilhada` (`descricao`, `observacao`, `status`) VALUES ('Churrasqueira', 'Dados ficticios para teste das telas', 'A');
SET @demo_area_compartilhada2 = LAST_INSERT_ID();
INSERT INTO `edificio` (`nome`, `quantidade_andares`, `quantidade_unidades`, `cnpj`, `ano_lancamento`, `area_total`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `numero_unidade_agua`, `numero_unidade_gas`, `formula_calculo`, `observacao`, `status`) VALUES ('Edificio Teste 2', 5, 10, '99000000000002', '2020', 1500.0, '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 2', 'AGUA-2', 'GAS-2', NULL, 'Dados ficticios para teste das telas', 'A');
SET @demo_edificio2 = LAST_INSERT_ID();
INSERT INTO `proprietario` (`nome_fantasia`, `razao_social`, `cpf`, `rg`, `cnpj`, `inscricao_estadual`, `fone1`, `fone2`, `email`, `data_nascimento`, `data_cadastro`, `estado_civil`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `observacao`, `status`) VALUES ('Bruno Teste', NULL, '90000000002', '1000002', NULL, NULL, '11999990002', NULL, 'teste2@example.com', '1990-05-12', '2026-10-01', 'Solteiro', '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 2', 'Dados ficticios para teste das telas', 'A');
SET @demo_proprietario2 = LAST_INSERT_ID();
INSERT INTO `unidade` (`descricao`, `metragem_total`, `metragem_individual`, `tipo_unidade`, `observacao`, `status`, `edificio_id`) VALUES ('Apartamento 102', 85.5, 70.0, 'Apartamento', 'Dados ficticios para teste das telas', 'A', @demo_edificio2);
SET @demo_unidade2 = LAST_INSERT_ID();
INSERT INTO `unidade_condomino` (`data_aquisicao`, `data_venda`, `observacao`, `status`, `proprietario_id`, `unidade_id`) VALUES ('2026-01-01', NULL, 'Dados ficticios para teste das telas', 'A', @demo_proprietario2, @demo_unidade2);
SET @demo_unidade_condomino2 = LAST_INSERT_ID();
INSERT INTO `area_compartilhada_edificio` (`observacao`, `status`, `area_compartilhada_id`, `edificio_id`) VALUES ('Dados ficticios para teste das telas', 'A', @demo_area_compartilhada2, @demo_edificio2);
SET @demo_area_compartilhada_edificio2 = LAST_INSERT_ID();
INSERT INTO `custo_nivel1` (`descricao`, `tipo_cc`, `observacao`, `status`) VALUES ('Servicos', 'Debito', 'Dados ficticios para teste das telas', 'A');
SET @demo_custo_nivel12 = LAST_INSERT_ID();
INSERT INTO `custo_nivel2` (`descricao`, `observacao`, `status`, `custo_nivel1_id`) VALUES ('Limpeza', 'Dados ficticios para teste das telas', 'A', @demo_custo_nivel12);
SET @demo_custo_nivel22 = LAST_INSERT_ID();
INSERT INTO `fornecedor` (`nome_fantasia`, `razao_social`, `cpf`, `rg`, `cnpj`, `inscricao_estadual`, `fone1`, `fone2`, `email`, `data_nascimento`, `data_cadastro`, `estado_civil`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `observacao`, `status`) VALUES ('Limpeza Teste', NULL, '90000000002', '1000002', '99000000000002', NULL, '11999990002', NULL, 'teste2@example.com', '1990-05-12', '2026-10-01', 'Solteiro', '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 2', 'Dados ficticios para teste das telas', 'A');
SET @demo_fornecedor2 = LAST_INSERT_ID();
INSERT INTO `sindico_profissional` (`cra`, `nome_fantasia`, `razao_social`, `cpf`, `rg`, `cnpj`, `inscricao_estadual`, `fone1`, `fone2`, `email`, `data_nascimento`, `data_cadastro`, `estado_civil`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `observacao`, `status`) VALUES ('TESTE-20261002-2', 'Maria Sindica Teste', NULL, '90000000002', '1000002', '99000000000002', NULL, '11999990002', NULL, 'teste2@example.com', '1990-05-12', '2026-10-01', 'Solteiro', '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 2', 'Dados ficticios para teste das telas', 'A');
SET @demo_sindico_profissional2 = LAST_INSERT_ID();
INSERT INTO `funcao_mandato` (`funcao`, `data_inicio`, `data_fim`, `observacao`, `status`, `edificio_id`, `proprietario_id`, `sindico_profissional_id`) VALUES ('Sindico', '2026-01-01', NULL, 'Dados ficticios para teste das telas', 'A', @demo_edificio2, @demo_proprietario2, @demo_sindico_profissional2);
SET @demo_funcao_mandato2 = LAST_INSERT_ID();
INSERT INTO `reserva` (`data_hora_inicio`, `data_hora_fim`, `observacao`, `status`, `area_compartilhada_edificio_id`, `unidade_condominio_id`) VALUES ('2026-10-05 14:00:00', '2026-10-05 18:00:00', 'Dados ficticios para teste das telas', 'A', @demo_area_compartilhada_edificio2, @demo_unidade_condomino2);
SET @demo_reserva2 = LAST_INSERT_ID();
INSERT INTO `leitura` (`data_leitura`, `mes_referencia`, `ano_referencia`, `medicao_anterior`, `medicao_atual`, `tipo`, `observacao`, `status`, `unidade_condomino_id`) VALUES ('2026-10-01', 10, 2026, 200.0, 215.5, 'Agua', 'Dados ficticios para teste das telas', 'A', @demo_unidade_condomino2);
SET @demo_leitura2 = LAST_INSERT_ID();
INSERT INTO `condominio` (`mes_referencia`, `ano_referencia`, `data_emissao`, `data_vencimento`, `data_pagamento`, `juros`, `multas`, `correcao`, `valor_emitido`, `valor_pago`, `observacao`, `status`, `unidade_condomino_id`) VALUES (10, 2026, '2026-10-01', '2026-10-10', NULL, 0, 0, 0, 350.0, NULL, 'Dados ficticios para teste das telas', 'A', @demo_unidade_condomino2);
SET @demo_condominio2 = LAST_INSERT_ID();
INSERT INTO `movimento_caixa` (`data_emissao`, `data_vencimento`, `data_pagamento`, `valor_emitido`, `multas`, `correcao_monetaria`, `juros`, `valor_pagamento`, `tipo`, `flag_rateio`, `flag_formula`, `observacao`, `status`, `edificio_id`, `custo_nivel2_id`, `fornecedor_id`) VALUES ('2026-10-01', '2026-10-10', NULL, 850.0, 0, 0, 0, NULL, 'Despesa', 1, NULL, 'Dados ficticios para teste das telas', 'A', @demo_edificio2, @demo_custo_nivel22, @demo_fornecedor2);
SET @demo_movimento_caixa2 = LAST_INSERT_ID();
INSERT INTO `area_compartilhada` (`descricao`, `observacao`, `status`) VALUES ('Piscina', 'Dados ficticios para teste das telas', 'I');
SET @demo_area_compartilhada3 = LAST_INSERT_ID();
INSERT INTO `edificio` (`nome`, `quantidade_andares`, `quantidade_unidades`, `cnpj`, `ano_lancamento`, `area_total`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `numero_unidade_agua`, `numero_unidade_gas`, `formula_calculo`, `observacao`, `status`) VALUES ('Edificio Teste 3', 5, 10, '99000000000003', '2020', 1500.0, '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 3', 'AGUA-3', 'GAS-3', NULL, 'Dados ficticios para teste das telas', 'I');
SET @demo_edificio3 = LAST_INSERT_ID();
INSERT INTO `proprietario` (`nome_fantasia`, `razao_social`, `cpf`, `rg`, `cnpj`, `inscricao_estadual`, `fone1`, `fone2`, `email`, `data_nascimento`, `data_cadastro`, `estado_civil`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `observacao`, `status`) VALUES ('Carla Teste', NULL, '90000000003', '1000003', NULL, NULL, '11999990003', NULL, 'teste3@example.com', '1990-05-12', '2026-10-01', 'Solteiro', '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 3', 'Dados ficticios para teste das telas', 'I');
SET @demo_proprietario3 = LAST_INSERT_ID();
INSERT INTO `unidade` (`descricao`, `metragem_total`, `metragem_individual`, `tipo_unidade`, `observacao`, `status`, `edificio_id`) VALUES ('Apartamento 201', 85.5, 70.0, 'Apartamento', 'Dados ficticios para teste das telas', 'I', @demo_edificio3);
SET @demo_unidade3 = LAST_INSERT_ID();
INSERT INTO `unidade_condomino` (`data_aquisicao`, `data_venda`, `observacao`, `status`, `proprietario_id`, `unidade_id`) VALUES ('2026-01-01', NULL, 'Dados ficticios para teste das telas', 'I', @demo_proprietario3, @demo_unidade3);
SET @demo_unidade_condomino3 = LAST_INSERT_ID();
INSERT INTO `area_compartilhada_edificio` (`observacao`, `status`, `area_compartilhada_id`, `edificio_id`) VALUES ('Dados ficticios para teste das telas', 'I', @demo_area_compartilhada3, @demo_edificio3);
SET @demo_area_compartilhada_edificio3 = LAST_INSERT_ID();
INSERT INTO `custo_nivel1` (`descricao`, `tipo_cc`, `observacao`, `status`) VALUES ('Administracao', 'Debito', 'Dados ficticios para teste das telas', 'I');
SET @demo_custo_nivel13 = LAST_INSERT_ID();
INSERT INTO `custo_nivel2` (`descricao`, `observacao`, `status`, `custo_nivel1_id`) VALUES ('Taxas administrativas', 'Dados ficticios para teste das telas', 'I', @demo_custo_nivel13);
SET @demo_custo_nivel23 = LAST_INSERT_ID();
INSERT INTO `fornecedor` (`nome_fantasia`, `razao_social`, `cpf`, `rg`, `cnpj`, `inscricao_estadual`, `fone1`, `fone2`, `email`, `data_nascimento`, `data_cadastro`, `estado_civil`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `observacao`, `status`) VALUES ('Servicos Teste', NULL, '90000000003', '1000003', '99000000000003', NULL, '11999990003', NULL, 'teste3@example.com', '1990-05-12', '2026-10-01', 'Solteiro', '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 3', 'Dados ficticios para teste das telas', 'I');
SET @demo_fornecedor3 = LAST_INSERT_ID();
INSERT INTO `sindico_profissional` (`cra`, `nome_fantasia`, `razao_social`, `cpf`, `rg`, `cnpj`, `inscricao_estadual`, `fone1`, `fone2`, `email`, `data_nascimento`, `data_cadastro`, `estado_civil`, `cep`, `logradouro`, `cidade`, `bairro`, `complemento`, `observacao`, `status`) VALUES ('TESTE-20261002-3', 'Pedro Sindico Teste', NULL, '90000000003', '1000003', '99000000000003', NULL, '11999990003', NULL, 'teste3@example.com', '1990-05-12', '2026-10-01', 'Solteiro', '01001000', 'Rua de Teste', 'Sao Paulo', 'Centro', 'Numero 3', 'Dados ficticios para teste das telas', 'I');
SET @demo_sindico_profissional3 = LAST_INSERT_ID();
INSERT INTO `funcao_mandato` (`funcao`, `data_inicio`, `data_fim`, `observacao`, `status`, `edificio_id`, `proprietario_id`, `sindico_profissional_id`) VALUES ('Sindico', '2026-01-01', NULL, 'Dados ficticios para teste das telas', 'I', @demo_edificio3, @demo_proprietario3, @demo_sindico_profissional3);
SET @demo_funcao_mandato3 = LAST_INSERT_ID();
INSERT INTO `reserva` (`data_hora_inicio`, `data_hora_fim`, `observacao`, `status`, `area_compartilhada_edificio_id`, `unidade_condominio_id`) VALUES ('2026-10-05 14:00:00', '2026-10-05 18:00:00', 'Dados ficticios para teste das telas', 'I', @demo_area_compartilhada_edificio3, @demo_unidade_condomino3);
SET @demo_reserva3 = LAST_INSERT_ID();
INSERT INTO `leitura` (`data_leitura`, `mes_referencia`, `ano_referencia`, `medicao_anterior`, `medicao_atual`, `tipo`, `observacao`, `status`, `unidade_condomino_id`) VALUES ('2026-10-01', 10, 2026, 300.0, 315.5, 'Agua', 'Dados ficticios para teste das telas', 'I', @demo_unidade_condomino3);
SET @demo_leitura3 = LAST_INSERT_ID();
INSERT INTO `condominio` (`mes_referencia`, `ano_referencia`, `data_emissao`, `data_vencimento`, `data_pagamento`, `juros`, `multas`, `correcao`, `valor_emitido`, `valor_pago`, `observacao`, `status`, `unidade_condomino_id`) VALUES (10, 2026, '2026-10-01', '2026-10-10', NULL, 0, 0, 0, 350.0, NULL, 'Dados ficticios para teste das telas', 'I', @demo_unidade_condomino3);
SET @demo_condominio3 = LAST_INSERT_ID();
INSERT INTO `movimento_caixa` (`data_emissao`, `data_vencimento`, `data_pagamento`, `valor_emitido`, `multas`, `correcao_monetaria`, `juros`, `valor_pagamento`, `tipo`, `flag_rateio`, `flag_formula`, `observacao`, `status`, `edificio_id`, `custo_nivel2_id`, `fornecedor_id`) VALUES ('2026-10-01', '2026-10-10', NULL, 850.0, 0, 0, 0, NULL, 'Despesa', 1, NULL, 'Dados ficticios para teste das telas', 'I', @demo_edificio3, @demo_custo_nivel23, @demo_fornecedor3);
SET @demo_movimento_caixa3 = LAST_INSERT_ID();
