/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.menu;

import controller.cadastro.CadastroCustoNivel1Controller;
import controller.cadastro.CadastroMovimentoCaixaController;
import controller.cadastro.CadastroUnidadeController;
import controller.cadastro.CadastroCondominioController;
import controller.cadastro.CadastroCustoNivel2Controller;
import controller.cadastro.CadastroProprietarioController;
import controller.cadastro.CadastroSindicoProfissionalController;
import controller.cadastro.CadastroAreaCompartilhadaController;
import controller.cadastro.CadastroUnidadeCondominoController;
import controller.cadastro.CadastroFuncaoMandatoController;
import controller.cadastro.CadastroFornecedorController;
import controller.cadastro.CadastroLeituraController;
import controller.cadastro.CadastroEdificioController;
import controller.cadastro.CadastroReservaController;
import view.cadastro.*;

/**
 *
 * @author luiz
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName());

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelTextoTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSubtitulo = new javax.swing.JLabel();
        jPanelModulos = new javax.swing.JPanel();
        jButtonEdificio = new javax.swing.JButton();
        jButtonCondominio = new javax.swing.JButton();
        jButtonUnidade = new javax.swing.JButton();
        jButtonProprietario = new javax.swing.JButton();
        jButtonFornecedor = new javax.swing.JButton();
        jButtonReserva = new javax.swing.JButton();
        jPanelRodape = new javax.swing.JPanel();
        jLabelRodape = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemEdificio = new javax.swing.JMenuItem();
        jSeparatorCadastro1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCondominio = new javax.swing.JMenuItem();
        jMenuItemUnidade = new javax.swing.JMenuItem();
        jSeparatorCadastro2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemProprietario = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItemSindico = new javax.swing.JMenuItem();
        jMenuItemFuncaoMandato = new javax.swing.JMenuItem();
        jMenuItemUnidadeCondomino = new javax.swing.JMenuItem();
        jSeparatorCadastro3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAreaCompartilhada = new javax.swing.JMenuItem();
        jMenuOperacoes = new javax.swing.JMenu();
        jMenuItemLeitura = new javax.swing.JMenuItem();
        jMenuItemMovimentoCaixa = new javax.swing.JMenuItem();
        jMenuItemReserva = new javax.swing.JMenuItem();
        jSeparatorOperacoes1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCustoNivel1 = new javax.swing.JMenuItem();
        jMenuItemCustoNivel2 = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestao de Condominio");
        setMinimumSize(new java.awt.Dimension(680, 460));
        setResizable(false);

        jPanelTitulo.setBackground(new java.awt.Color(21, 67, 96));
        jPanelTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 20, 12, 20));

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Company.png"))); // NOI18N

        jPanelTextoTitulo.setOpaque(false);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Sistema de Gestao de Condominio");

        jLabelSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelSubtitulo.setForeground(new java.awt.Color(174, 214, 241));
        jLabelSubtitulo.setText("Selecione um modulo para comecar");

        javax.swing.GroupLayout jPanelTextoTituloLayout = new javax.swing.GroupLayout(jPanelTextoTitulo);
        jPanelTextoTitulo.setLayout(jPanelTextoTituloLayout);
        jPanelTextoTituloLayout.setHorizontalGroup(
            jPanelTextoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTextoTituloLayout.setVerticalGroup(
            jPanelTextoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextoTituloLayout.createSequentialGroup()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSubtitulo))
        );

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jPanelTextoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanelTextoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelModulos.setBackground(new java.awt.Color(240, 244, 248));
        jPanelModulos.setBorder(javax.swing.BorderFactory.createEmptyBorder(22, 20, 22, 20));
        jPanelModulos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 18, 22));

        jButtonEdificio.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEdificio.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButtonEdificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Company.png"))); // NOI18N
        jButtonEdificio.setText("<html><center>Edificio<br><small>Cadastro de edificios [F1]</small></center></html>");
        jButtonEdificio.setFocusPainted(false);
        jButtonEdificio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEdificio.setPreferredSize(new java.awt.Dimension(188, 158));
        jButtonEdificio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEdificio.addActionListener(this::jButtonEdificioActionPerformed);
        jPanelModulos.add(jButtonEdificio);

        jButtonCondominio.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCondominio.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButtonCondominio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Home.png"))); // NOI18N
        jButtonCondominio.setText("<html><center>Condominio<br><small>Dados do condominio [F2]</small></center></html>");
        jButtonCondominio.setFocusPainted(false);
        jButtonCondominio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCondominio.setPreferredSize(new java.awt.Dimension(188, 158));
        jButtonCondominio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCondominio.addActionListener(this::jButtonCondominioActionPerformed);
        jPanelModulos.add(jButtonCondominio);

        jButtonUnidade.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUnidade.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButtonUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Diagram.png"))); // NOI18N
        jButtonUnidade.setText("<html><center>Unidade<br><small>Unidades do condominio [F3]</small></center></html>");
        jButtonUnidade.setFocusPainted(false);
        jButtonUnidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUnidade.setPreferredSize(new java.awt.Dimension(188, 158));
        jButtonUnidade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonUnidade.addActionListener(this::jButtonUnidadeActionPerformed);
        jPanelModulos.add(jButtonUnidade);

        jButtonProprietario.setBackground(new java.awt.Color(255, 255, 255));
        jButtonProprietario.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButtonProprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Person.png"))); // NOI18N
        jButtonProprietario.setText("<html><center>Proprietario<br><small>Moradores e proprietarios [F4]</small></center></html>");
        jButtonProprietario.setFocusPainted(false);
        jButtonProprietario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProprietario.setPreferredSize(new java.awt.Dimension(188, 158));
        jButtonProprietario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProprietario.addActionListener(this::jButtonProprietarioActionPerformed);
        jPanelModulos.add(jButtonProprietario);

        jButtonFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        jButtonFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButtonFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Briefcase.png"))); // NOI18N
        jButtonFornecedor.setText("<html><center>Fornecedor<br><small>Prestadores de servico [F5]</small></center></html>");
        jButtonFornecedor.setFocusPainted(false);
        jButtonFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFornecedor.setPreferredSize(new java.awt.Dimension(188, 158));
        jButtonFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFornecedor.addActionListener(this::jButtonFornecedorActionPerformed);
        jPanelModulos.add(jButtonFornecedor);

        jButtonReserva.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReserva.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButtonReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calendar.png"))); // NOI18N
        jButtonReserva.setText("<html><center>Reservas<br><small>Reserva de areas comuns</small></center></html>");
        jButtonReserva.setFocusPainted(false);
        jButtonReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReserva.setPreferredSize(new java.awt.Dimension(188, 158));
        jButtonReserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonReserva.addActionListener(this::jButtonReservaActionPerformed);
        jPanelModulos.add(jButtonReserva);

        jPanelRodape.setBackground(new java.awt.Color(213, 219, 227));

        jLabelRodape.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabelRodape.setForeground(new java.awt.Color(90, 100, 115));
        jLabelRodape.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRodape.setText("Sistema de Gestao de Condominio  v1.0");

        javax.swing.GroupLayout jPanelRodapeLayout = new javax.swing.GroupLayout(jPanelRodape);
        jPanelRodape.setLayout(jPanelRodapeLayout);
        jPanelRodapeLayout.setHorizontalGroup(
            jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRodapeLayout.setVerticalGroup(
            jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRodape)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemEdificio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemEdificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Company.png"))); // NOI18N
        jMenuItemEdificio.setText("Edificio");
        jMenuItemEdificio.addActionListener(this::jMenuItemEdificioActionPerformed);
        jMenuCadastro.add(jMenuItemEdificio);
        jMenuCadastro.add(jSeparatorCadastro1);

        jMenuItemCondominio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemCondominio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Home.png"))); // NOI18N
        jMenuItemCondominio.setText("Condominio");
        jMenuItemCondominio.addActionListener(this::jMenuItemCondominioActionPerformed);
        jMenuCadastro.add(jMenuItemCondominio);

        jMenuItemUnidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Diagram.png"))); // NOI18N
        jMenuItemUnidade.setText("Unidade");
        jMenuItemUnidade.addActionListener(this::jMenuItemUnidadeActionPerformed);
        jMenuCadastro.add(jMenuItemUnidade);
        jMenuCadastro.add(jSeparatorCadastro2);

        jMenuItemProprietario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemProprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Person.png"))); // NOI18N
        jMenuItemProprietario.setText("Proprietario");
        jMenuItemProprietario.addActionListener(this::jMenuItemProprietarioActionPerformed);
        jMenuCadastro.add(jMenuItemProprietario);

        jMenuItemFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Briefcase.png"))); // NOI18N
        jMenuItemFornecedor.setText("Fornecedor");
        jMenuItemFornecedor.addActionListener(this::jMenuItemFornecedorActionPerformed);
        jMenuCadastro.add(jMenuItemFornecedor);

        jMenuItemSindico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Boss_1.png"))); // NOI18N
        jMenuItemSindico.setText("Sindico Profissional");
        jMenuItemSindico.addActionListener(this::jMenuItemSindicoActionPerformed);
        jMenuCadastro.add(jMenuItemSindico);

        jMenuItemFuncaoMandato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clipboard.png"))); // NOI18N
        jMenuItemFuncaoMandato.setText("Funcao de Mandato");
        jMenuItemFuncaoMandato.addActionListener(this::jMenuItemFuncaoMandatoActionPerformed);
        jMenuCadastro.add(jMenuItemFuncaoMandato);

        jMenuItemUnidadeCondomino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/People.png"))); // NOI18N
        jMenuItemUnidadeCondomino.setText("Unidade Condomino");
        jMenuItemUnidadeCondomino.addActionListener(this::jMenuItemUnidadeCondominoActionPerformed);
        jMenuCadastro.add(jMenuItemUnidadeCondomino);
        jMenuCadastro.add(jSeparatorCadastro3);

        jMenuItemAreaCompartilhada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Globe.png"))); // NOI18N
        jMenuItemAreaCompartilhada.setText("Area Compartilhada");
        jMenuItemAreaCompartilhada.addActionListener(this::jMenuItemAreaCompartilhadaActionPerformed);
        jMenuCadastro.add(jMenuItemAreaCompartilhada);

        jMenuBar1.add(jMenuCadastro);

        jMenuOperacoes.setText("Operacoes");

        jMenuItemLeitura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Equipment.png"))); // NOI18N
        jMenuItemLeitura.setText("Leitura de Medidores");
        jMenuItemLeitura.addActionListener(this::jMenuItemLeituraActionPerformed);
        jMenuOperacoes.add(jMenuItemLeitura);

        jMenuItemMovimentoCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Dollar.png"))); // NOI18N
        jMenuItemMovimentoCaixa.setText("Movimento de Caixa");
        jMenuItemMovimentoCaixa.addActionListener(this::jMenuItemMovimentoCaixaActionPerformed);
        jMenuOperacoes.add(jMenuItemMovimentoCaixa);

        jMenuItemReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calendar.png"))); // NOI18N
        jMenuItemReserva.setText("Reservas");
        jMenuItemReserva.addActionListener(this::jMenuItemReservaActionPerformed);
        jMenuOperacoes.add(jMenuItemReserva);
        jMenuOperacoes.add(jSeparatorOperacoes1);

        jMenuItemCustoNivel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Database.png"))); // NOI18N
        jMenuItemCustoNivel1.setText("Custo Nivel 1");
        jMenuItemCustoNivel1.addActionListener(this::jMenuItemCustoNivel1ActionPerformed);
        jMenuOperacoes.add(jMenuItemCustoNivel1);

        jMenuItemCustoNivel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Database.png"))); // NOI18N
        jMenuItemCustoNivel2.setText("Custo Nivel 2");
        jMenuItemCustoNivel2.addActionListener(this::jMenuItemCustoNivel2ActionPerformed);
        jMenuOperacoes.add(jMenuItemCustoNivel2);

        jMenuBar1.add(jMenuOperacoes);

        jMenuSobre.setText("Sobre");

        jMenuItemSobre.setText("Sistema de Gestao de Condominio v1.0");
        jMenuItemSobre.setEnabled(false);
        jMenuSobre.add(jMenuItemSobre);

        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelModulos, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
            .addComponent(jPanelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelModulos, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEdificioActionPerformed
        abrirEdificio();
    }//GEN-LAST:event_jMenuItemEdificioActionPerformed

    private void jMenuItemCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCondominioActionPerformed
        abrirCondominio();
    }//GEN-LAST:event_jMenuItemCondominioActionPerformed

    private void jMenuItemUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnidadeActionPerformed
        abrirUnidade();
    }//GEN-LAST:event_jMenuItemUnidadeActionPerformed

    private void jMenuItemProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProprietarioActionPerformed
        abrirProprietario();
    }//GEN-LAST:event_jMenuItemProprietarioActionPerformed

    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
        abrirFornecedor();
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    private void jMenuItemSindicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSindicoActionPerformed
        abrirSindico();
    }//GEN-LAST:event_jMenuItemSindicoActionPerformed

    private void jMenuItemFuncaoMandatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncaoMandatoActionPerformed
        abrirFuncaoMandato();
    }//GEN-LAST:event_jMenuItemFuncaoMandatoActionPerformed

    private void jMenuItemUnidadeCondominoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnidadeCondominoActionPerformed
        abrirUnidadeCondomino();
    }//GEN-LAST:event_jMenuItemUnidadeCondominoActionPerformed

    private void jMenuItemAreaCompartilhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAreaCompartilhadaActionPerformed
        abrirAreaCompartilhada();
    }//GEN-LAST:event_jMenuItemAreaCompartilhadaActionPerformed

    private void jMenuItemLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLeituraActionPerformed
        abrirLeitura();
    }//GEN-LAST:event_jMenuItemLeituraActionPerformed

    private void jMenuItemMovimentoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMovimentoCaixaActionPerformed
        abrirMovimentoCaixa();
    }//GEN-LAST:event_jMenuItemMovimentoCaixaActionPerformed

    private void jMenuItemReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReservaActionPerformed
        abrirReserva();
    }//GEN-LAST:event_jMenuItemReservaActionPerformed

    private void jMenuItemCustoNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustoNivel1ActionPerformed
        abrirCustoNivel1();
    }//GEN-LAST:event_jMenuItemCustoNivel1ActionPerformed

    private void jMenuItemCustoNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustoNivel2ActionPerformed
        abrirCustoNivel2();
    }//GEN-LAST:event_jMenuItemCustoNivel2ActionPerformed

    private void jButtonEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdificioActionPerformed
        abrirEdificio();
    }//GEN-LAST:event_jButtonEdificioActionPerformed

    private void jButtonCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCondominioActionPerformed
        abrirCondominio();
    }//GEN-LAST:event_jButtonCondominioActionPerformed

    private void jButtonUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnidadeActionPerformed
        abrirUnidade();
    }//GEN-LAST:event_jButtonUnidadeActionPerformed

    private void jButtonProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProprietarioActionPerformed
        abrirProprietario();
    }//GEN-LAST:event_jButtonProprietarioActionPerformed

    private void jButtonFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornecedorActionPerformed
        abrirFornecedor();
    }//GEN-LAST:event_jButtonFornecedorActionPerformed

    private void jButtonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservaActionPerformed
        abrirReserva();
    }//GEN-LAST:event_jButtonReservaActionPerformed

    // ── abrir forms ─────────────────────────────────────────────────────────

    private void abrirEdificio() {
        TelaCadastroEdificio tela = new TelaCadastroEdificio(null, true);
        new CadastroEdificioController(tela);
        tela.setVisible(true);
    }

    private void abrirCondominio() {
        TelaCadastroCondominio tela = new TelaCadastroCondominio(null, true);
        new CadastroCondominioController(tela);
        tela.setVisible(true);
    }

    private void abrirUnidade() {
        TelaCadastroUnidade tela = new TelaCadastroUnidade(null, true);
        new CadastroUnidadeController(tela);
        tela.setVisible(true);
    }

    private void abrirProprietario() {
        TelaCadastroProprietario tela = new TelaCadastroProprietario(null, true);
        new CadastroProprietarioController(tela);
        tela.setVisible(true);
    }

    private void abrirFornecedor() {
        TelaCadastroFornecedor tela = new TelaCadastroFornecedor(null, true);
        new CadastroFornecedorController(tela);
        tela.setVisible(true);
    }

    private void abrirSindico() {
        TelaCadastroSindicoProfissional tela = new TelaCadastroSindicoProfissional(null, true);
        new CadastroSindicoProfissionalController(tela);
        tela.setVisible(true);
    }

    private void abrirFuncaoMandato() {
        TelaCadastroFuncaoMandato tela = new TelaCadastroFuncaoMandato(null, true);
        new CadastroFuncaoMandatoController(tela);
        tela.setVisible(true);
    }

    private void abrirUnidadeCondomino() {
        TelaCadastroUnidadeCondomino tela = new TelaCadastroUnidadeCondomino(null, true);
        new CadastroUnidadeCondominoController(tela);
        tela.setVisible(true);
    }

    private void abrirAreaCompartilhada() {
        TelaCadastroAreaCompartilhada tela = new TelaCadastroAreaCompartilhada(null, true);
        new CadastroAreaCompartilhadaController(tela);
        tela.setVisible(true);
    }

    private void abrirLeitura() {
        TelaCadastroLeitura tela = new TelaCadastroLeitura(null, true);
        new CadastroLeituraController(tela);
        tela.setVisible(true);
    }

    private void abrirMovimentoCaixa() {
        TelaCadastroMovimentoCaixa tela = new TelaCadastroMovimentoCaixa(null, true);
        new CadastroMovimentoCaixaController(tela);
        tela.setVisible(true);
    }

    private void abrirReserva() {
        TelaCadastroReserva tela = new TelaCadastroReserva(null, true);
        new CadastroReservaController(tela);
        tela.setVisible(true);
    }

    private void abrirCustoNivel1() {
        TelaCadastroCustoNivel1 tela = new TelaCadastroCustoNivel1(null, true);
        new CadastroCustoNivel1Controller(tela);
        tela.setVisible(true);
    }

    private void abrirCustoNivel2() {
        TelaCadastroCustoNivel2 tela = new TelaCadastroCustoNivel2(null, true);
        new CadastroCustoNivel2Controller(tela);
        tela.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCondominio;
    private javax.swing.JButton jButtonEdificio;
    private javax.swing.JButton jButtonFornecedor;
    private javax.swing.JButton jButtonProprietario;
    private javax.swing.JButton jButtonReserva;
    private javax.swing.JButton jButtonUnidade;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelRodape;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAreaCompartilhada;
    private javax.swing.JMenuItem jMenuItemCondominio;
    private javax.swing.JMenuItem jMenuItemCustoNivel1;
    private javax.swing.JMenuItem jMenuItemCustoNivel2;
    private javax.swing.JMenuItem jMenuItemEdificio;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemFuncaoMandato;
    private javax.swing.JMenuItem jMenuItemLeitura;
    private javax.swing.JMenuItem jMenuItemMovimentoCaixa;
    private javax.swing.JMenuItem jMenuItemProprietario;
    private javax.swing.JMenuItem jMenuItemReserva;
    private javax.swing.JMenuItem jMenuItemSindico;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemUnidade;
    private javax.swing.JMenuItem jMenuItemUnidadeCondomino;
    private javax.swing.JMenu jMenuOperacoes;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanelModulos;
    private javax.swing.JPanel jPanelRodape;
    private javax.swing.JPanel jPanelTextoTitulo;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPopupMenu.Separator jSeparatorCadastro1;
    private javax.swing.JPopupMenu.Separator jSeparatorCadastro2;
    private javax.swing.JPopupMenu.Separator jSeparatorCadastro3;
    private javax.swing.JPopupMenu.Separator jSeparatorOperacoes1;
    // End of variables declaration//GEN-END:variables
}
